on:
    workflow_dispatch:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

name: Validate and publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run validate
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs
          retention-days: 1
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
